/**
 *class OligoException: handles exceptions generated by Oligo class methods
 *@version 1.0 (08/01/2007) - start of class implementation
 */
public class OligoException extends Exception
{
    private String error;
    private String method;
    
    OligoException(String e, String m)
    {
        error = e;
        method = m;
    }
    
    OligoException(String e)
    {
        error = e;
        method = "";
    }

    public String toString()
    {
        return "OligoException[" +method+ "]: " + error;
    }
} //end OligoException class
